### ISSUE TITLE
Compilation of HACL* on bare metal targets

### ISSUE THREAD

**Issue by podhrmic** [hacl-star/hacl-star#47] opened 2017-10-02 16:34 UTC
Hello,

the generated C code does not compile for bare-metal embedded targets (i.e. no OS). The problem is calling `printf()` and `exit()` functions (for example here https://github.com/mitls/hacl-star/blob/master/snapshots/hacl-c/kremlib.h#L76 ).

Another thing is missing defines for `htolen64()` and similar for non-linux embedded targets - there probably have to be defined manually (here is an example here https://github.com/jedisct1/libhydrogen/blob/v0/impl/common.h ).

I can manually edit the generated `kremlin.h` file to get it working, but I doubt that is the right way to go. I am happy to edit the template for autogenerated files if you can point me in the right direction.

How does removing `printf()` and `exit()` (or defining them as empty functions for bare-metal targets) affects the verification proof?

**Comment by karthikbhargavan** [comment] 2017-10-02 16:52
printf and exit are not used in the crypto code, they are primarily used
for testing. so this should not affect verification.

editing kremlib to remove these and defining htolen64 etc would be a good
starting point.
if it works then we can think of a more principled way of doing this.

**Comment by podhrmic** [comment] 2017-10-06 04:36
@karthikbhargavan thanks for the hint, please have a look at my new PRs

**Comment by msprotz** [comment] 2017-10-06 08:15
I'm happy to consider changes to `kremlib.h` to make your life easier (it's a copy of the original file at https://github.com/FStarLang/kremlin/blob/master/kremlib/kremlib.h)... I'll ping you here when I have a revised version. Thanks for the suggestions!

**Comment by podhrmic** [comment] 2017-10-06 15:59
@msprotz thanks!

**Comment by msprotz** [comment] 2017-10-09 14:43
I believe this is fixed by https://github.com/FStarLang/kremlin/commit/276bbd4ee67414109b5e88627cd7e2eda4eab73e

**Comment by beurdouche** [comment] 2017-10-09 15:58
@podhrmic Can you have a look to see if it works for you before I close the issue ?

**Comment by podhrmic** [comment] 2017-11-20 02:50
Hi @beurdouche sorry I missed the notification here.

It works as expected, just tested it. Is there a reason this new `kremlin.h/c` is not yet in the main repository? (here https://github.com/mitls/hacl-star/blob/master/snapshots/kremlib/kremlib.h )

Also, on a different note - there is still a lot of warnings for unused variables in the C snapshot (at least from GCC). Is that something you are planning to resolve?

**Comment by beurdouche** [comment] 2017-11-20 09:09
No worries, I am pushing a new version of HACL* in Firefox/NSS this week and we are currently changing Kremlib so that it doesn't import too much... So the new Kremlib will be in HACL* this week.
Unused variable should disapear more and more (can you please open an issue and point me to those) because code generarion is improving. Warnings related to unused static inline functions should also disapear more and more.

**Comment by podhrmic** [comment] 2017-11-20 20:03
OK, I ll post the unused variables warnings once the new kremlib is up.

**Comment by podhrmic** [comment] 2017-11-29 05:25
@beurdouche here are the unused variables from latest hacl-c snapshot:

```
snapshots/hacl-c/AEAD_Poly1305_64.c: In function 'Hacl_Impl_Poly1305_64_poly1305_process_last_block_':
snapshots/hacl-c/AEAD_Poly1305_64.c:200:12: warning: unused parameter 'm' [-Wunused-parameter]
   uint8_t *m,
            ^
snapshots/hacl-c/AEAD_Poly1305_64.c:201:12: warning: unused parameter 'rem_' [-Wunused-parameter]
   uint64_t rem_
            ^~~~
snapshots/hacl-c/AEAD_Poly1305_64.c: In function 'AEAD_Poly1305_64_seval':
snapshots/hacl-c/AEAD_Poly1305_64.c:338:40: warning: unused parameter 'b' [-Wunused-parameter]
 Prims_nat AEAD_Poly1305_64_seval(void *b)
                                        ^
snapshots/hacl-c/AEAD_Poly1305_64.c: In function 'AEAD_Poly1305_64_selem':
snapshots/hacl-c/AEAD_Poly1305_64.c:344:40: warning: unused parameter 's' [-Wunused-parameter]
 Prims_int AEAD_Poly1305_64_selem(void *s)
                                        ^
snapshots/hacl-c/Hacl_Ed25519.c: In function 'Hacl_Impl_Ed25519_Ladder_Step_loop_step_1':
snapshots/hacl-c/Hacl_Ed25519.c:1092:65: warning: unused parameter 'k1' [-Wunused-parameter]
 Hacl_Impl_Ed25519_Ladder_Step_loop_step_1(uint64_t *b, uint8_t *k1, uint32_t ctr, uint8_t i)
                                                                 ^~
snapshots/hacl-c/Hacl_Ed25519.c:1092:78: warning: unused parameter 'ctr' [-Wunused-parameter]
 Hacl_Impl_Ed25519_Ladder_Step_loop_step_1(uint64_t *b, uint8_t *k1, uint32_t ctr, uint8_t i)
                                                                              ^~~
snapshots/hacl-c/Hacl_Ed25519.c: In function 'Hacl_Impl_Ed25519_Ladder_Step_loop_step_2':
snapshots/hacl-c/Hacl_Ed25519.c:1100:77: warning: unused parameter 'k1' [-Wunused-parameter]
 static void Hacl_Impl_Ed25519_Ladder_Step_loop_step_2(uint64_t *b, uint8_t *k1, uint32_t ctr)
                                                                             ^~
snapshots/hacl-c/Hacl_Ed25519.c:1100:90: warning: unused parameter 'ctr' [-Wunused-parameter]
 static void Hacl_Impl_Ed25519_Ladder_Step_loop_step_2(uint64_t *b, uint8_t *k1, uint32_t ctr)
                                                                                          ^~~
snapshots/hacl-c/Hacl_Ed25519.c: In function 'Hacl_Impl_Ed25519_Ladder_Step_loop_step_3':
snapshots/hacl-c/Hacl_Ed25519.c:1111:65: warning: unused parameter 'k1' [-Wunused-parameter]
 Hacl_Impl_Ed25519_Ladder_Step_loop_step_3(uint64_t *b, uint8_t *k1, uint32_t ctr, uint8_t i)
                                                                 ^~
snapshots/hacl-c/Hacl_Ed25519.c:1111:78: warning: unused parameter 'ctr' [-Wunused-parameter]
 Hacl_Impl_Ed25519_Ladder_Step_loop_step_3(uint64_t *b, uint8_t *k1, uint32_t ctr, uint8_t i)
                                                                              ^~~
snapshots/hacl-c/Hacl_Ed25519.c: In function 'Hacl_Impl_Ed25519_SecretToPublic_secret_to_public_':
snapshots/hacl-c/Hacl_Ed25519.c:1491:12: warning: unused parameter 'secret' [-Wunused-parameter]
   uint8_t *secret,
            ^~~~~~
snapshots/hacl-c/Hacl_Ed25519.c: In function 'Hacl_Impl_Ed25519_RecoverX_recover_x_':
snapshots/hacl-c/Hacl_Ed25519.c:1767:17: warning: declaration of 'x2' shadows a previous local [-Wshadow]
       uint64_t *x2 = tmp;
                 ^~
snapshots/hacl-c/Hacl_Ed25519.c:1713:12: note: shadowed declaration is here
   uint64_t x2 = y[2U];
            ^~
snapshots/hacl-c/Hacl_Ed25519.c:1768:17: warning: declaration of 'x30' shadows a previous local [-Wshadow]
       uint64_t *x30 = tmp + (uint32_t)5U;
                 ^~~
snapshots/hacl-c/Hacl_Ed25519.c:1714:12: note: shadowed declaration is here
   uint64_t x30 = y[3U];
            ^~~
snapshots/hacl-c/Hacl_Ed25519.c:1790:17: warning: declaration of 'x20' shadows a previous local [-Wshadow]
       uint64_t *x20 = tmp;
                 ^~~
snapshots/hacl-c/Hacl_Ed25519.c:1710:13: note: shadowed declaration is here
   uint64_t *x20 = tmp;
             ^~~
snapshots/hacl-c/Hacl_Ed25519.c: In function 'Hacl_Impl_Ed25519_Sign_Steps_sign_step_4':
snapshots/hacl-c/Hacl_Ed25519.c:2763:12: warning: unused variable 'apre' [-Wunused-variable]
   uint8_t *apre = tmp_bytes + (uint32_t)224U;
            ^~~~
```

Hope that helps.

**Comment by beurdouche** [comment] 2017-11-29 18:21
Ok, the AEAD ones will disappear as soon as we can delete that file.
The Ed25519 `unused parameters` and `unused variables`, I can reproduce with `-Wall -Wextra` and I will try do something about it...
The Ed25519 `shadows a previous declaration` are actually that the compiler is too dumb. I think it  might be solved by generating C89 code instead of C99, but we'll have to try. What compiler options did you use to generate them ?

**Comment by podhrmic** [comment] 2017-11-30 00:29
I am using `arm-none-abi-gcc` with `-std=gnu99` option.

**Comment by podhrmic** [comment] 2018-04-09 16:04
@beurdouche thanks! I am planning to update the hacl-c snapshot I am using for pprzlink in next few weeks, will let you know how that goes:-)

**Comment by msprotz** [comment] 2022-11-03 17:13
The original issue was fixed and the discussion moved onto unused variables, which is tracked in #583

**Closed by msprotz** 2022-11-03 17:13 UTC
Labels: enhancement, P2, meta
