### ISSUE TITLE
Testing of Chacha20Poly1305 doesn't work (missing some Evercrypt header)

### ISSUE THREAD

**Issue by beurdouche** [hacl-star/hacl-star#412] opened 2021-03-04 07:58 UTC
Running make in `code/chacha20poly1305` fails.
```
/opt/fstar/bin/fstar.exe --use_hints --use_hint_hashes --record_hints --odir ../../obj --cache_checked_modules --include ../../lib --include ../../specs --include ../../specs/lemmas --include ../../specs/tests --include ../../specs/drbg --include ../../specs/ecdsap256 --include ../../specs/frodo --include ../../code/hash --include ../../code/hmac --include ../../code/hkdf --include ../../code/drbg --include ../../code/hpke --include ../../code/sha3 --include ../../code/ecdsap256 --include ../../code/poly1305 --include ../../code/streaming --include ../../code/blake2 --include ../../code/chacha20 --include ../../code/chacha20poly1305 --include ../../code/curve25519 --include ../../code/tests --include ../../code/ed25519 --include ../../code/salsa20 --include ../../code/nacl-box --include ../../code/meta --include ../../code/frodo --include ../../code/fallback --include ../../code/bignum --include ../../code/rsapss --include ../../code/ffdhe --include ../../vale/code/arch --include ../../vale/code/arch/x64 --include ../../vale/code/arch/x64/interop --include ../../vale/code/crypto/aes --include ../../vale/code/crypto/aes/x64 --include ../../vale/code/crypto/bignum --include ../../vale/code/crypto/ecc/curve25519 --include ../../vale/code/crypto/poly1305 --include ../../vale/code/crypto/poly1305/x64 --include ../../vale/code/crypto/sha --include ../../vale/code/lib/collections --include ../../vale/code/lib/math --include ../../vale/code/lib/util --include ../../vale/code/lib/util/x64 --include ../../vale/code/lib/util/x64/stdcalls --include ../../vale/code/lib/transformers --include ../../vale/code/test --include ../../vale/code/thirdPartyPorts/Intel/aes/x64 --include ../../vale/code/thirdPartyPorts/OpenSSL/aes --include ../../vale/code/thirdPartyPorts/OpenSSL/poly1305/x64 --include ../../vale/code/thirdPartyPorts/OpenSSL/sha --include ../../vale/code/thirdPartyPorts/rfc7748/curve25519/x64 --include ../../vale/code/thirdPartyPorts/SymCrypt/bignum --include ../../vale/specs/crypto --include ../../vale/specs/defs --include ../../vale/specs/hardware --include ../../vale/specs/interop --include ../../vale/specs/math --include ../../providers/evercrypt --include ../../providers/evercrypt/fst --include ../../providers/test --include ../../providers/test/vectors --include ../../providers/evercrypt/config/default --include ../../secure_api/merkle_tree --include /opt/kremlin/runtime --include ../../obj --include /opt/fstar/ulib/.cache --include /opt/kremlin/kremlib/obj --include /opt/kremlin/kremlib --cmi --already_cached 'Prims FStar LowStar C Spec.Loops TestLib WasmSupport' --warn_error '+241@247-272' --cache_dir ../../obj --trivial_pre_for_unannotated_effectful_fns false --warn_error @332 --dep full Hacl.Chacha20Poly1305_128.fst Hacl.Chacha20Poly1305_256.fst Hacl.Chacha20Poly1305_32.fst Hacl.Impl.Chacha20Poly1305.PolyCore.fst Hacl.Impl.Chacha20Poly1305.fst Hacl.Meta.Chacha20Poly1305.fst \
    --extract '-* +FStar.Kremlin.Endianness +Vale.Arch +Vale.X64 -Vale.X64.MemoryAdapters +Vale.Def +Vale.Lib +Vale.Bignum.X64 -Vale.Lib.Tactics +Vale.Math +Vale.Transformers +Vale.AES +Vale.Interop +Vale.Arch.Types +Vale.Arch.BufferFriend +Vale.Lib.X64 +Vale.SHA.X64 +Vale.SHA.SHA_helpers +Vale.Curve25519.X64 +Vale.Poly1305.X64 +Vale.Inline +Vale.AsLowStar +Vale.Test +Spec +Lib -Lib.IntVector +C' \
    > .depend
cc -Idist -I/opt/kremlin/include -I/opt/kremlin/kremlib/dist/minimal -I../../../lib/c -I../../lib/c -march=native -mtune=native   -c -o ../../tests/chacha20poly1305-test.o ../../tests/chacha20poly1305-test.c
../../tests/chacha20poly1305-test.c:15:10: fatal error: 'EverCrypt_AutoConfig2.h' file not found
#include "EverCrypt_AutoConfig2.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
gmake: *** [<builtin>: ../../tests/chacha20poly1305-test.o] Error 1
```

**Comment by polubelova** [comment] 2021-03-04 09:38
It only works with the global dist, i.e. it can be run like this:
```
hacl-star/dist/gcc-compatible$ ./configure
hacl-star/dist/gcc-compatible$ CC=gcc-9 make -j6
hacl-star/dist/gcc-compatible$ cd ../../tests/
hacl-star/tests$ CC=gcc-9 make -j6
hacl-star/tests$ ./chacha20poly1305-test.exe 
```

Maybe @msprotz knows how to make it work again with local Makefiles?
(I usually comment out this include locally which is not the best solution :))

**Comment by msprotz** [comment] 2021-03-04 15:05
@beurdouche: can you try adding dist/gcc-compatible to the include path?

@polubelova:
basically the problem is that this test file runs both the scalar, 128 and 256 tests in a single file; without splitting these tests into three separate files, you have to rely on macros to make sure the file compiles on non-128, non-256 systems -- right now, the only way to achieve this reliably is through running the configure script; unfortunately, the logic is becoming so complex with x86, x64, arm, Z and power that we have to relyon this sort of stuff to make compilation work

**Comment by msprotz** [comment] 2021-03-04 15:06
@Kachoc and I have discussed this repeatedly and have come to the conclusion that there should be one test file per vectorization level (just like there is one C file for each one of 32, 128 and 256 variants) -- then, the Makefile can decide which files to compile, and if you do that, you don't need to insert #ifdefs everywhere

**Comment by beurdouche** [comment] 2021-03-06 17:51
> @Kachoc and I have discussed this repeatedly and have come to the conclusion that there should be one test file per vectorization level (just like there is one C file for each one of 32, 128 and 256 variants) -- then, the Makefile can decide which files to compile, and if you do that, you don't need to insert #ifdefs everywhere

I agree that having one test/caller file per version is needed. We can still have one shared file for the input/output values.

**Comment by msprotz** [comment] 2022-12-15 17:06
I believe this is all fixed, since the tests have been split according to the level of CPU support they require. Closing.

**Closed by msprotz** 2022-12-15 17:06 UTC
Labels: bug, P1, tests
